server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/events/*/comments/**,/users/*/comments/**,/admin/comments/**

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**,/admin/events/**,/users/*/events/**,/events/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**